 # This is the configuration used to check the rubocop source code.
AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
  NewCops: enable
Style/Documentation:
  Enabled: false
Layout:
  Max: 99
Rails/HasAndBelongsToMany:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
# rubocop-rspec custom configurations
require:
  - rubocop-rails
  - rubocop-rspec
Naming/VariableNumber:
  EnforcedStyle: snake_case
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
Rails/FilePath:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 10
  Exclude:
    - spec/support/**/*